# Generated by Django 3.2 on 2021-05-06 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todo_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_color',
            field=models.CharField(default='rgb(255,255,0,1)', max_length=20),
        ),
        migrations.AlterField(
            model_name='column',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board', to='api.board'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='column', to='api.column'),
        ),
    ]
